# Generated by Django 4.1.7 on 2023-04-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='business_add',
            field=models.CharField(max_length=33, null=True, verbose_name='사업자주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='business_name',
            field=models.CharField(max_length=33, null=True, verbose_name='사업자상호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('0', '군포')], max_length=18, null=True, verbose_name='지역'),
        ),
    ]
