# Generated by Django 4.1.7 on 2023-04-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paesu_record',
            name='ck_advise',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='지도사항'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='ck_holiday',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='휴일체크'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='ck_remarks',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='특이사항'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='ck_temperature',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='기온'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='ck_weather',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='날씨'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='sluge_corp',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='위탁처리업소명'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='sluge_func',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='슬러지함수률'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='sluge_gene',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='슬러지발생량'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='sluge_keep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='슬러지보관량'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='sluge_place',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='슬러지보관장소'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='sluge_selfplace',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='슬러지처리장소'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='sluge_used',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='슬러지처리량'),
        ),
    ]
