# Generated by Django 4.1.7 on 2023-04-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_alter_paesu_record_ck_advise_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paesu_record',
            name='유저 기록 unique key',
        ),
        migrations.RenameField(
            model_name='paesu_record',
            old_name='ck_advise',
            new_name='advise',
        ),
        migrations.RenameField(
            model_name='paesu_record',
            old_name='ck_temperature',
            new_name='date_temperature',
        ),
        migrations.RenameField(
            model_name='paesu_record',
            old_name='ck_weather',
            new_name='date_weather',
        ),
        migrations.RemoveField(
            model_name='paesu_record',
            name='ck_date',
        ),
        migrations.RemoveField(
            model_name='paesu_record',
            name='ck_holiday',
        ),
        migrations.RemoveField(
            model_name='paesu_record',
            name='ck_remarks',
        ),
        migrations.RemoveField(
            model_name='paesu_record',
            name='genwaster_prevd',
        ),
        migrations.RemoveField(
            model_name='paesu_record',
            name='genwaster_today',
        ),
        migrations.RemoveField(
            model_name='paesu_record',
            name='genwaster_used',
        ),
        migrations.RemoveField(
            model_name='paesu_record',
            name='med1_mz',
        ),
        migrations.RemoveField(
            model_name='paesu_record',
            name='med2_mz',
        ),
        migrations.RemoveField(
            model_name='paesu_record',
            name='med3_mz',
        ),
        migrations.RemoveField(
            model_name='paesu_record',
            name='med4_mz',
        ),
        migrations.RemoveField(
            model_name='paesu_record',
            name='poweruse_time',
        ),
        migrations.RemoveField(
            model_name='paesu_record',
            name='reuse_prevd',
        ),
        migrations.RemoveField(
            model_name='paesu_record',
            name='reuse_today',
        ),
        migrations.RemoveField(
            model_name='paesu_record',
            name='reuse_used',
        ),
        migrations.RemoveField(
            model_name='paesu_record',
            name='underwater_time',
        ),
        migrations.RemoveField(
            model_name='paesu_record',
            name='waterworks_time',
        ),
        migrations.AddField(
            model_name='paesu_record',
            name='date',
            field=models.DateField(null=True, verbose_name='일자'),
        ),
        migrations.AddField(
            model_name='paesu_record',
            name='date_ck',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='휴일'),
        ),
        migrations.AddField(
            model_name='paesu_record',
            name='diswaste_ck',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='폐수배출량 사용유무'),
        ),
        migrations.AddField(
            model_name='paesu_record',
            name='genwaster',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='폐수발생량'),
        ),
        migrations.AddField(
            model_name='paesu_record',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='특기사항'),
        ),
        migrations.AddField(
            model_name='paesu_record',
            name='reuse',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='재사용량'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='diswaste_prevd',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='폐수배출량 전일'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='diswaste_today',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='폐수배출량 금일'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='diswaste_used',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='폐수배출량 사용량'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='poweruse_end',
            field=models.CharField(choices=[('1', '1시'), ('2', '2시'), ('3', '3시'), ('4', '4시'), ('5', '5시'), ('6', '6시'), ('7', '7시'), ('8', '8시'), ('9', '9시'), ('10', '10시'), ('11', '11시'), ('12', '12시'), ('13', '13시'), ('14', '14시'), ('15', '15시'), ('16', '16시'), ('17', '17시'), ('18', '18시'), ('19', '19시'), ('20', '20시'), ('21', '21시'), ('22', '22시'), ('23', '23시'), ('24', '24시')], default=18, max_length=10, verbose_name='전산전력계지침 가동 종료시간'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='poweruse_prevd',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='전산전력계지침 전일'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='poweruse_start',
            field=models.CharField(choices=[('1', '1시'), ('2', '2시'), ('3', '3시'), ('4', '4시'), ('5', '5시'), ('6', '6시'), ('7', '7시'), ('8', '8시'), ('9', '9시'), ('10', '10시'), ('11', '11시'), ('12', '12시'), ('13', '13시'), ('14', '14시'), ('15', '15시'), ('16', '16시'), ('17', '17시'), ('18', '18시'), ('19', '19시'), ('20', '20시'), ('21', '21시'), ('22', '22시'), ('23', '23시'), ('24', '24시')], default=9, max_length=10, verbose_name='전산전력계지침 가동 시작시간'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='poweruse_today',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='전산전력계지침 금일'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='poweruse_used',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='전산전력계지침 사용량 '),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='sluge_corp',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='슬러지 위탁처리업소명'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='sluge_func',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='슬러지 함수율(%)'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='sluge_gene',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='슬러지 발생량'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='sluge_keep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='슬러지 보관량'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='sluge_place',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='슬러지 보관장소'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='sluge_selfplace',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='슬러지 처리장소'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='sluge_used',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='슬러지 처리량'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='underwater_prevd',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='지하수 전일'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='underwater_today',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='지하수 금일'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='underwater_used',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='지하수 사용량'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='waterworks_prevd',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='상수도 전일'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='waterworks_today',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='상수도 금일'),
        ),
        migrations.AlterField(
            model_name='paesu_record',
            name='waterworks_used',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='상수도 사용량'),
        ),
        migrations.AddConstraint(
            model_name='paesu_record',
            constraint=models.UniqueConstraint(fields=('date', 'date_ck'), name='유저 기록 unique key'),
        ),
    ]
